;; This logfile was generated automatically by `xindy'
;; at 14.03.2017  22:35:57
;; Indexstyle: "D:\\Files\\Documents\\masters\\UCoGH2Y_L4", Rawindex: "D:\\Files\\Documents\\masters\\pPvR9RwIxt", Output: "Bfriedensein_Masters.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "Ú¤Ð" -> "T"