This is makeindex, version 2.15 [MiKTeX 2.9.6210 64-bit] (kpathsea + Thai support).
Scanning style file ./Bfriedensein_Masters.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Bfriedensein_Masters.acn....done (14 entries accepted, 0 rejected).
Sorting entries....done (49 comparisons).
Generating output file Bfriedensein_Masters.acr....done (21 lines written, 0 warnings).
Output written in Bfriedensein_Masters.acr.
Transcript written in Bfriedensein_Masters.alg.
